import { mkdir, copyFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const dist = path.join(root, 'dist');

async function ensureDir(p) {
  await mkdir(p, { recursive: true });
}

async function copy(src, dest) {
  await ensureDir(path.dirname(dest));
  await copyFile(src, dest);
}

// Make these routes work on static hosts that don't support "clean URLs":
// - /style-two.html
// - /style-three.html
//
// We copy the folder index pages generated by Vite:
// - dist/style-two/index.html -> dist/style-two.html
// - dist/style-three/index.html -> dist/style-three.html
await copy(path.join(dist, 'style-two', 'index.html'), path.join(dist, 'style-two.html'));
await copy(path.join(dist, 'style-three', 'index.html'), path.join(dist, 'style-three.html'));

console.log('postbuild: wrote dist/style-two.html and dist/style-three.html');

